[UI/#14] 공통컴포넌트(dialog) 구현
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #15
Opened 2024-11-20 12:38 UTC by jangsjw

## Related issue 🛠
- closed #14 

## Work Description ✏️
- 공통컴포넌트(dialog) 구현 

## Screenshot 📸
<img width="311" alt="image" src="https://github.com/user-attachments/assets/c09425f0-c9ec-407b-99a1-eca8e58b8d53">

## To Reviewers (Optional) 📢
수정사항 반영해서 만들어봤습니다!! 피드백주세요!

2024-11-20 13:02 UTC, boiledEgg-s requested changes
너무 잘하셨습니다! 
수정해야할 부분을 댓글로 남겼으니 다시 구현해보시고 리뷰 재요청 보내주세요!!

2024-11-20 13:02 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +    modifier: Modifier = Modifier
하나의 컴포저블에서 또다른 컴포저블 함수를 받아서 사용할 수 있어요!
다이얼로그의 경우, 제목과 아이콘을 포함하는 오렌지 색깔의 상단바를 제외한 내부 내용물들이 많이 달라요.

따라서 내부 내용은 외부에서 주입받을 수 있도록 다음과 같이 수정하면 좋을 것 같아요!
```suggestion
@Composable
fun CustomDialog(
    title: String,
    icon: ImageVector
    modifier: Modifier = Modifier,
    onIconClick: () -> Unit = {},
    content: @Composable () -> Unit = {}
```

위와 같이 바꾸게 되면 제목과 아이콘, 그리고 아이콘을 터치하는 이벤트만 이 함수에서 관리하면 되고, content 같은 경우 올바른 위치에 선언만 해주면 됩니다! 이 함수의 `message section`과 `button section`을 `content` 하나로 대체하면 될 것 같아요!

2024-11-20 13:02 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +        modifier = Modifier
`Dialog`라는 다이얼로그를 위한 컴포저블 함수가 존재합니다!
이 컴포저블을 사용하면 외부 영역 색상을 자동으로 어둡게 바꾸거나, 외부 영역을 터치하면 다이얼로그가 닫히게 하는 등, 다이얼로그를 위한 여러 로직을 제공해요!

`Dialog`를 사용해서 수정해봅시다!

2024-11-20 13:02 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                Column(
이 메시지 섹션과 그 밑의 버튼 섹션을 첫 코멘트에서 적은 `content` 컴포저블 함수로 대체하면 될 것 같아요!

2024-11-20 17:46 UTC, boiledEgg-s requested changes
아까 의식하지 못한 부분들이 있었네요! 확인하고 수정 부탁드려요~

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +
여기에 주석 달아주세요!

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +        ) {
`Card` 컴포저블을 사용할 필요는 없어 보입니다!

밑에 `Column`의 수정자에 width, padding, wrapContentHeight() 들을 옮겨주시고, background 속성을 추가해서 shape를 지정해주시면 될 것 같아요!

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                        .background(Color(0xFFFF6F00))
피그마에서 구현하는 컴포넌트를 클릭하면 우측 메뉴의 Fill 부분에서 컴포넌트에 사용된 색상의 이름을 확인할 수 있습니다!
프로젝트에서 사용되는 모든 색상을 프로젝트에 추가해두었으니, 색상코드 대신 `ShinMunGoTheme.color`에 정의된 색상을 사용하시면 됩니다!

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                        style = MaterialTheme.typography.headlineSmall.copy(
폰트도 마찬가지로 피그마에서 텍스트를 클릭하면 우측메뉴의 Typography 부분에서 스타일을 확인할 수 있습니다!
`ShinMunGoTheme.typography`를 사용하여 알맞은 스타일을 찾아서 사용하시면 됩니다!

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                        color = Color.White,
`ShinMunGoTheme.color`

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                modifier = Modifier.background(Color.White)
`ShinMunGoTheme.color`, 하단 코멘트 참고

2024-11-20 17:46 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                            tint = Color.White
여기도 `ShinMunGoTheme` 사용

2024-11-21 06:58 UTC, boiledEgg-s requested changes
이번이 마지막 수정 요청이 될 것 같네요~ 수정하고 재요청해주세요!

2024-11-21 06:58 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                .padding(16.dp)
이 패딩은 제거해주셔야 할 것 같아요! 여기에 패딩을 적용하니까 다이얼로그 외부 영역이 다이얼로그의 컨텐츠 영역을 침범하네요,, 

피그마를 보시고 다이얼로그의 너비를 335dp로 지정하셨을텐데, 이렇게 하니까 실제 너비가 303dp가 됩니다😅

2024-11-21 06:58 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
> +                        .background(ShinMunGoTheme.color.primary)
프리뷰 확인해보니까 다이얼로그의 상단 모서리들이 둥글지 않더라고요?
`Row`가 상단 `Column` 위를 덮다보니까 발생하는 문제같아요!

Row의 background에도 shape 속성을 추가해서 상단 모서리만 8.dp로 고정하면 좋을 것 같습니다!
```suggestion
                        .background(
                              color = ShinMunGoTheme.color.primary,
                              shape = RoundedCornerShape(topStart=8.dp, topEnd=8.dp)
                        )
```

2024-11-21 06:58 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/example/CustomDialog.kt
여기 패키지가 명시되어있지 않네요?
모든 코드 파일의 상단엔 `package com.sopt.shinmungo.core.designsystem.component.example`와 같은 식으로 파일이 속한 패키지 경로가 명시되어있어야 합니다!

그리고 example 패키지는 제가 예시를 담아두려고 만든 임시 패키지입니다!
component 밑에 dialog 패키지를 만들어서 관리해주세요!

2024-11-21 12:12 UTC, boiledEgg-s approved these changes
완벽합니다! 수고 많으셨어요~

2024-11-21 13:22 UTC, chrin05 approved these changes
석준오빠가 이미 잘 리뷰 달아줘서 추가로 달게 없네요..
구현하시느라 고생하셨습니다!!

2024-11-22 05:38 UTC, merged