[UI/#18] 버튼 컴포넌트 구현
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #19
Opened 2024-11-21 10:35 UTC by chrin05

## Related issue 🛠
- closed #18 

## Work Description ✏️
아래의 버튼 컴포넌트들 구현
- 테두리O+아이콘 버튼
- 테두리O+텍스트 버튼
- 테두리X+텍스트 버튼
- 글자+info아이콘 버튼
- 체크박스+글자+info 아이콘 버튼

## Screenshot 📸
<img width="429" alt="image" src="https://github.com/user-attachments/assets/795c4274-a395-4746-847f-de5b6c3289e1">
<img width="429" alt="image" src="https://github.com/user-attachments/assets/07f8a58d-d3fa-4287-8c2a-b8d6ec981cda">
<img width="429" alt="image" src="https://github.com/user-attachments/assets/b0c23944-c9a3-4194-a0a5-c12e79b922af">
<img width="429" alt="image" src="https://github.com/user-attachments/assets/de25a7ff-d7b7-4d10-996a-62dd750c6708">
<img width="429" alt="image" src="https://github.com/user-attachments/assets/34a9b27e-1f88-422d-b1f3-281654f3bd73">

## Uncompleted Tasks 😅
> 아직 구현이 안됐거나 미흡한 부분이 있다면 작성해주세요.
- 없습니다

## To Reviewers (Optional) 📢
> 리뷰어가 특별히 봐줬으면 하는 부분이 있다면 작성해주세요.
BaseRoundedCornerTextButton을 바탕으로 여러가지 텍스트 버튼 만들어두었으니 이 컴포저블은 직접 사용하지 않는 걸 권장합니다
**텍스트 버튼은 주로 인자로 넘겨주는 modifier에 가로,세로 값을 주어 조절하여 사용가능합니다.**
아직 부족해서 보완할 부분들이 있을 거 같은데, 수정해야할 부분들이 보이면 피드백 주세요!!

2024-11-21 12:50 UTC, yihwanggeun reviewed
일단 사소한 부분 의견 남겼으니까 봐주세요! 어푸는 리더님 의견도 보고 할게요!

2024-11-21 12:50 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +fun BaseRoundedCornerTextButton_With_Border_Preview(modifier: Modifier = Modifier) {
모든 경우를 다 Preview를 만들어주시다니,,, 감동

2024-11-21 12:50 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerTextButton.kt
> +                .height(49.dp),
제 개인적인 의견인데 절대적인 값을 넣는 것보다 Padding을 활용해서 하는 거 더 안정성이 높지 않을까라는 생각이 듭니다!

2024-11-21 12:50 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerWithBorderTextButton.kt
> +fun RoundedCornerWithBorderTextButton(
세세하게 구현해주신 거 진짜 대박,,,,
근데 그러다보니까 안에 내용들이 많이 겹치는 것 같아요
흠,,,BaseRoundedCornerTextButton를 좀 더 General하게 만들고 그걸 이용하는 방식은 어떨까요?

2024-11-21 12:50 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +fun CheckButtonWithTextInfoIcon(
이 부분을 `Button`이라고 생각해서 구현하신 이유가 궁금해요

2024-11-21 12:50 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +            contentDescription = "체크아이콘",
저도 깜빡하는데 스트링 추출해주시면 좋을 것 같아요!

2024-11-21 13:03 UTC, boiledEgg-s requested changes
너무 깔끔하네요!😮
로직만 조금 수정하면 좋을 것 같습니다~!!!!!

2024-11-21 13:03 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +    val lineColor = if (isBorderApplied) borderLineColor else backgroundColor
이 부분은 borderLineColor이 null인지 확인하는걸로 대체할 수 있을 것 같아요!
그러면 `isBorderApplied`라는 변수를 추가하지 않아도 되겠죠?

2024-11-21 13:03 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +            .border(width = 1.dp, color = lineColor!!, shape = roundedCornerShape),
`!!` 연산자는 NPE를 발생시킬 여지가 있기 때문에 왠만하면 사용하지 않는게 좋습니다! 
lineColor와 같이 nullable한 변수는 사용하기 전에 널체크를 하는 것이 좋습니다.

제가 추천드리는 코드는 정답은 아니기 때문에 참고만 해주세요~
```suggestion
        modifier = modifier
            .clip(roundedCornerShape)
            .background(backgroundColor)
            .then(
                  lineColor?.let { Modifier.border(width = 1.dp, color = it, shape = roundedCornerShape) } ?: Modifier
            )
```

2024-11-21 13:03 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +    buttonOnClick: () -> Unit,
이벤트 핸들러 함수는 보통 `on`을 맨앞에 붙여서 사용하는 것으로 알고 있어요!
팀내 코드 컨벤션을 맞추는게 좋으니까 수정부탁드립니다~

추가적으로 컴포저블의 파라미터 순서는 "필수 -> 수정자 -> 선택"입니다.
textStyle과 textColor가 modifier의 밑으로 들어와야 하는 것이죠!

2024-11-21 13:05 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerWithBorderTextButton.kt
> +fun RoundedCornerWithBorderTextButton(
좋은 의견이네요! 네이밍 신경써주면 관리가 편해지죠ㅎㅎ

2024-11-21 13:05 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +fun BaseRoundedCornerTextButton_With_Border_Preview(modifier: Modifier = Modifier) {
ㄹㅇ 레전드 감동

2024-11-21 13:38 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerTextButton.kt
> +                .height(49.dp),
네! 반영하겠습니다

2024-11-21 13:44 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerWithBorderTextButton.kt
> +fun RoundedCornerWithBorderTextButton(
> 세세하게 구현해주신 거 진짜 대박,,,, 근데 그러다보니까 안에 내용들이 많이 겹치는 것 같아요 흠,,,BaseRoundedCornerTextButton를 좀 더 General하게 만들고 그걸 이용하는 방식은 어떨까요?

버튼마다 폰트 스타일과 배경색, 글자색, 둥근 정도가 모두 조금씩 달라서 인자로 다 넣긴 했는데,, 좀 더 General하게 어떤 부분을 바꿀 수 있는지 힌트를 살짝 주실 수 있을까요?! (어떻게 변경해야할지 딱 안떠올라서..🥲)

2024-11-21 13:45 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +fun CheckButtonWithTextInfoIcon(
이 부분도 사용자가 터치하는 하나의 선택 영역이라고 생각해서 구현했습니다!

2024-11-21 13:45 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +            contentDescription = "체크아이콘",
넵 참고해서 수정하겠습니다

2024-11-21 13:51 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +    val lineColor = if (isBorderApplied) borderLineColor else backgroundColor
아하 그런 방법이 있었군요 반영하도록 하겠습니다

2024-11-21 13:58 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundedCornerWithBorderTextButton.kt
> +fun RoundedCornerWithBorderTextButton(
아 혹시 그냥 BaseRounedCornerTextButton 하나만으로 구현하는 것을 말하는걸까요? 아래 코드리뷰 적어주신 거 수정하다보니 이 BaseRounedCornerTextButton 컴포넌트 하나로 다 구현할 수 있을 거 같아서요..!

2024-11-21 14:05 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/BaseRoundedCornerTextButton.kt
> +            .border(width = 1.dp, color = lineColor!!, shape = roundedCornerShape),
위에 코드리뷰 달아주신 부분 수정하니 자동으로 수정되었습니다!

2024-11-21 14:05 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/CheckButtonWithTextInfoIcon.kt
> +    buttonOnClick: () -> Unit,
넵 관련해서 수정하겠습니다

2024-11-21 15:13 UTC, boiledEgg-s approved these changes
딱 하나만 더 확인해주시면 어프드릴게요ㅎㅎ

2024-11-21 15:13 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
> +            .noRippleClickable { onButtonClick() },
Modifier는 순서가 중요합니다.
padding 이후에 clickable이 선언되면 터치 영역이 줄어들게 돼요!
이런 부분도 신경써서 사용성을 해치지 않도록 합시다~

2024-11-21 15:15 UTC, boiledEgg-s commented
실수로 어프 줬는데 저것만 수정해주세요ㅎㅎ
정말 수고많으셨슴당~

2024-11-21 15:33 UTC, jangsjw commented
너무 고생하셨습니다..!! 코드 관련 수정은 위에서 해주셨고 저보다 채린님이 더 잘 아실 것 같아서 궁금한 점만 적겠습니다!! 제 뷰에 있는 신고하기 버튼은 채린님이 만들어주신 선택하기 버튼을 활용해서 하면 되는 건가요?!?

2024-11-21 15:33 UTC, jangsjw approved these changes

2024-11-22 01:10 UTC, chrin05 commented
> 너무 고생하셨습니다..!! 코드 관련 수정은 위에서 해주셨고 저보다 채린님이 더 잘 아실 것 같아서 궁금한 점만 적겠습니다!! 제 뷰에 있는 신고하기 버튼은 채린님이 만들어주신 선택하기 버튼을 활용해서 하면 되는 건가요?!?

네 맞습니다! 선택하기 Preview 참고해서 해당 코드처럼 사용하시면 됩니다!

2024-11-22 01:19 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
> +            .noRippleClickable { onButtonClick() },
오 넵 놓친 부분인데 감사합니다

2024-11-22 07:54 UTC, merged