[UI/#17] 탑바 컴포넌트 구현
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #20
Opened 2024-11-21 12:27 UTC by yihwanggeun

## Related issue 🛠
- closed #17

## Work Description ✏️
CommonTopBar 컴포넌트 구현

### 중앙 영역 (Title)
Text 컴포넌트를 사용하여 중앙 정렬된 타이틀 표시

### 좌측 영역 (Navigation Icon)
커스텀 가능한 Composable 영역 제공
컴포넌트 간 8dp 간격 유지

### 우측 영역 (Actions)
커스텀 가능한 Composable 영역 제공
컴포넌트 간 8dp 간격 유지

## 사용 예시
1. 기본 타이틀만 있는 TopBar
```kotlin
CommonTopBar(
    title = "메인화면"
)
```

2. 뒤로가기 아이콘 있는 TopBar
```kotlin
CommonTopBar(
    title = "상세화면",
    onLeftContent = {
        IconButton(
            modifier = Modifier.size(24.dp),
            onClick = { navController.popBackStack() }
        ) {
            Icon(
                painter = painterResource(id = R.drawable.ic_arrow_left_line_white_24),
                contentDescription = "Back",
                modifier = Modifier.size(24.dp),
                tint = ShinMunGoTheme.color.gray1
            )
        }
    }
)
```

3. 우측 아이콘 있는 TopBar
```kotlin
CommonTopBar(
    title = "채팅방",
    onRightContent = {
        IconButton(
            modifier = Modifier.size(24.dp),
            onClick = { /* 채팅 메뉴 실행 */ }
        ) {
            Icon(
                painter = painterResource(id = R.drawable.ic_chat_line_white_24),
                contentDescription = "Chat",
                modifier = Modifier.size(24.dp),
                tint = ShinMunGoTheme.color.gray1
            )
        }
    }
)
```
## Screenshot 📸
<img width="332" alt="image" src="https://github.com/user-attachments/assets/62d8f042-0741-42e5-a2d5-7a2d616aec91">

## Uncompleted Tasks 😅
> 아직 구현이 안됐거나 미흡한 부분이 있다면 작성해주세요.
- [ ] 

## To Reviewers (Optional) 📢
> 생각보다 공통 Component 쪽에서 설정해야 하는 게 적어서 디자인시에 세세한 고려를 해주셔야 할 것 같습니다.

2024-11-21 13:18 UTC, boiledeggg requested changes
너무 깔끔하게 잘하셨습니다! 이분 엄살이 심하시다~

댓글 한번 확인해주시고 재요청 보내주세요!!

2024-11-21 13:18 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/topbar/CommonTopBar.kt
> +                modifier = Modifier.padding(start = 8.dp),
navigationIcon과 action에서 좌우 패딩을 관리하는 것보다 TopAppBar의 Modifier를 사용하여 한 곳에서 관리하는게 좋을 것 같습니다!

2024-11-21 15:36 UTC, jangsjw commented
너무 고생하셨습니다!! 코드 관련해서는 저보다 잘 아실 것 같아서 궁금증만 남겼습니다!!!!

2024-11-21 15:36 UTC, jangsjw approved these changes

2024-11-21 15:36 UTC, jangsjw commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/topbar/CommonTopBar.kt
> +        },
여기 텍스트 부분은 나중에 label만 수정해서 사용하는 건가요?!?!

2024-11-22 01:09 UTC, chrin05 approved these changes
구현하시느라 고생하셨습니다! 👍

2024-11-22 04:20 UTC, boiledEgg-s approved these changes
너무 수고하셨습니다~ 
다음부터 수정하시면 Reviewers에 리뷰 재요청 보내주세요!!

2024-11-22 05:48 UTC, merged