[UI#27] 전체 카테고리(신고/View2)
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #29
Opened 2024-11-24 09:37 UTC by jangsjw

## Related issue 🛠
- closed #27 

## Work Description ✏️
- 전체 카테고리(신고/View2) UI 구현
- 
## Screenshot 📸
<img width="214" alt="image" src="https://github.com/user-attachments/assets/3f82f6aa-5ca5-41d3-959a-469e4c6b9c8a">

## Uncompleted Tasks 😅
- [ ] discription 부분 서버 연결

## To Reviewers (Optional) 📢
discription API 연결 빼고 한 것 같은데...확신은 없네요ㅠ + 첫 커밋 제목 실수ㅎㅎ..

2024-11-24 13:40 UTC, boiledEgg-s requested changes
너무 수고하셨습니다!!
수정사항 반영해보시고 재요청! 잊지 말고 보내주세요!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/allCategoryComponent.kt
> +                        ).forEach { item ->
내부 목록은 카테고리마다 다르기 때문에 이 부분도 ReportCategoryItem를 호출할 때 파라미터로 넣어줄 수 있도록 고쳐봅시다!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +fun PreviewReportCategoryItem() {
컴포넌트 프리뷰는 컴포넌트가 정의된 파일에 넣어주세요~

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +)
따로 파일에 빼두신 것 같은데 이 부분은 지워주세요!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +            )
UI들 머지가 완료되면 나중에 화면 전환 작업을 하게 될텐데 그때 바텀바가 카테고리화면에도 뜰 수 있도록 작업할거에요!
여기에서 바텀바는 지워주시면 됩니다!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +                    text = "전체 메뉴",
이렇게 UI 코드에 문자열이나 숫자를 직접 기입하는 것을 하드코딩이라고 합니다. 
이렇게 하드코딩을 하게 되면 나중에 문자열을 수정해야 할 때 찾고 고치기 어렵기 때문에 문자열을 리소스로 변환해서 관리하는 것을 추천합니다.

하드코딩된 문자열과 숫자들이 더 있다면 리소스화 부탁드려요~

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +    val expandedStates = remember { mutableStateListOf(false, false, false, false) }
이렇게 관리하는 방법도 좋지만 저는 변수를 각각 따로 만들어서 관리하는 것을 추천드립니다!
어떤 카테고리 박스를 관리하는 변수인지 변수명에 잘 적어 넣으면 지금보다 코드 가독성이 매우 좋아질거에요!!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +                )
이런 컴포넌트들은 `allcategory/component` 패키지에 집어넣어서 화면 자체에 대한 코드를 깔끔하게 유지하시면 더 좋을 것 같아요!
만약 탑바의 메커니즘이 궁금하다면 파일을 탐색하면 되겠죠?

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +package com.sopt.shinmungo.presentation.allcategory.screen
스크린 파일은 `screen`이라는 패키지 없이 `allCategory` 바로 밑에서 관리해주세요!
또한 화면 자체를 관리하는 스크린 파일과 패키지명은 통일해주시길 바랍니다! `allcategory` 밑에 스크린 파일 이름이 `ReportCategory`면 코드를 읽는 사람이 혼동이 생길 것 같습니다!! 패키지 또는 파일 중 하나를 수정해주세요!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/screen/allCategory.kt
> +            LazyColumn(
LazyColumn이 충분히 Column 역할을 해줄텐데 왜 이중으로 선언하셨나요?

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/viewmodel/CategoryViewModel.kt
> +package com.sopt.shinmungo.presentation.allcategory.viewmodel
뷰모델 파일인데 뷰모델은 없고 엔티티가 들어있네요..?
파일의 목적을 파일명에 분명하게 선언해둬야 협업 시 혼동이 줄고 유지보수성이 올라갑니다!

또한 이렇게 핵심 정보를 포함하는 클래스를 엔티티라고 부릅니다! 6주차 세미나에서 배웠듯이 엔티티, 특히 서버를 통해 받아오는 값을 포함하는 엔티티는 `domain/entity`에 선언되어야 해요!! 
저희 프로젝트에도 `domain\entity` 패키지가 마련되어 있으니까 거기로 옮겨주세요!

2024-11-24 13:40 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/viewmodel/CategoryViewModel.kt
> +    val description: String
세부 카테고리들도 신고 유형마다 다르던데, 그 부분도 엔티티에 추가돼야 할 것 같네요!! 문자열 리스트로 관리해봅시다!

2024-11-25 01:43 UTC, yihwanggeun reviewed
기본적으로 깔끔하게 잘 짜주신 것 같아요!
로직적으로는 제가 조언을 못 드릴 것 같아서 짜잘짜잘한 피드백 드렸습니다!

2024-11-25 01:43 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryTopBar.kt
> +
이미 CommonTopBar에서 onLeftConetnt부분은  이미 Row로 감싸져 있어서 다시 한 번 안 감싸셔도 됩니다~!

2024-11-25 01:43 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +        if (isExpanded) {
혹시 If 문을 2개로 나눠둔 이유가 있을까요?

2024-11-25 01:43 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +                    contentDescription = "Info Icon",
String추출!

2024-11-25 01:43 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/AllCategoryScreen.kt
> +    viewModel: AllCategoryViewModel = hiltViewModel()
매개변수에 대한 주석이 있으면 좋을 것 같아요

2024-11-25 01:43 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +    onClick: () -> Unit
여기도 매개변수 주석 있으면 좋겠습니다!

2024-11-25 03:56 UTC, jangsjw commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +        if (isExpanded) {
엇 아뇨! 하나로 통합하겠습니다!!

2024-11-25 08:53 UTC, boiledEgg-s requested changes
피그마랑 코드 훑으면서 폰트값 확인 한번 해주세요~
수정하면 리뷰 재요청 잊지마시구요!

2024-11-25 08:53 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/AllCategoryScreen.kt
> +    viewModel: AllCategoryViewModel = hiltViewModel()
힐트를 안쓰고있기 때문에 hiltViewmodel 말고 viewModel() 사용해주세요!

2024-11-25 08:53 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +                    style = ShinMunGoTheme.typography.heading2.copy(fontSize = 15.sp),
폰트값 확인이랑 copy 빼주세요!

2024-11-25 08:53 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryTopBar.kt
> +        )
CommonTopBar의 title에 문자열을 넣으면 자동으로 제목이 생성될거에요!

2024-11-25 08:53 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +                        style = ShinMunGoTheme.typography.body3.copy(lineHeight = 20.sp),
폰트 확인!

2024-11-25 23:56 UTC, chrin05 approved these changes
고생하셨습니다!
전반적으로 다 잘 하신 거 같아요 자잘한 코멘트만 남겨놨습니다!

2024-11-25 23:56 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +                        .padding(vertical = 8.dp)
제가 컴포넌트 만들면서 preivew 만들때 신경을 못썼는데, width는 삭제하고 87번줄에 padding에 horizontal 속성값으로 20.dp를 주는 게 더 나은 방법 인 거 같습니다!

2024-11-25 23:56 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/allcategory/component/AllCategoryComponent.kt
> +                        }
지금 바로 수정해야할 부분은 아닌 거 같지만 코멘트를 남겨놓자면, 서버 측에서 각 카테고리마다 reportableItems 처럼 넘겨주는것이 아니라 string값으로 다 넘겨주는 것으로 알고 있습니다! 나중에 서버 연결하실 때 참고하시면 될 거 같아요!

2024-11-26 04:28 UTC, boiledEgg-s approved these changes

2024-11-26 05:28 UTC, merged