[UI/#31] dialog 구현
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #32
Opened 2024-11-25 03:20 UTC by jangsjw

## Related issue 🛠
- closed #31

## Work Description ✏️
- [x] 신고 완료 다이얼로그
- [x] 초기화 확인 다이얼로그
- [x] 사진 첨부 제한 시간 안내 다이얼로그
- [x] 사진 첨부 크기 제한 다이얼로그
- [x] 사진 삭제 확인 다이얼로그

## Screenshot 📸
<img width="221" alt="image" src="https://github.com/user-attachments/assets/06a25b73-cf25-43e4-9d09-6e6fadbbf543">

<img width="216" alt="image" src="https://github.com/user-attachments/assets/57dce8a0-1b59-42ac-b5d5-77d3e94cc087">

<img width="257" alt="image" src="https://github.com/user-attachments/assets/299e3cef-3e86-4376-9f27-7aaadf82e1bf">

<img width="254" alt="image" src="https://github.com/user-attachments/assets/7e193f15-749c-4502-8744-55bd0480d3b2">

<img width="255" alt="image" src="https://github.com/user-attachments/assets/8def9cef-a0d6-4550-b0db-38345e4a4ead">

## Uncompleted Tasks 😅

## To Reviewers (Optional) 📢
전체 다이얼로그 구현 했습니다!

2024-11-25 12:21 UTC, boiledEgg-s requested changes
너무 수고 많으셨습니당! 
문자열 리소스화만 해주시면 될 것 같아요~!!

2024-11-25 12:21 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/FireTruckIllegalParkingDialog.kt
> +                        contentDescription = "경고 아이콘",
하드코딩 지양해주세요~

2024-11-25 14:03 UTC, yihwanggeun reviewed
짜잘한 리뷰이지만 이런 방식이 더 좋을 수도 있을 것 같아 의견 남깁니다!

2024-11-25 14:03 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/FireTruckIllegalParkingDialog.kt
> +        modifier = Modifier.width(321.dp),
이렇게 321.dp 를 사용하면 다양한 화면에서 이상하게 보일 수도 있을 것 같아요
```kotlin
val screenWidth = LocalConfiguration.current.screenWidthDp.dp
val dialogWidth = screenWidth * 0.8f 
```

이런 방식도 있다고 하니 참고해주세요!

2024-11-25 14:03 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoDeleteConfirmationDialog.kt
> +                .width(281.dp)
이런 부분도 CustomDialog에서 Width를 잘 설정해두면 `fillMaxWidth()`를 사용해서 구현하면 더 깔끔하지 않을까 싶네요!

2024-11-25 15:49 UTC, jangsjw commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/FireTruckIllegalParkingDialog.kt
> +        modifier = Modifier.width(321.dp),
감사합니다! 수정해볼게용

2024-11-25 16:48 UTC, boiledeggg approved these changes
완벽한 다이얼로그입니당!! 너무 고생하셨어요!!
머지하기 전에 PR 메시지에 올라와있는 다이얼로그 스크린샷 수정된 버전으로 업데이트해주세요!!

2024-11-25 21:38 UTC, yihwanggeun approved these changes
어푸드립니다! 리더님이 말한 것처럼 스크린샷 수정본 올려주세요!

2024-11-26 00:25 UTC, chrin05 reviewed
구현하시느라 고생하셨습니다!
RoundedCornerTextButton이 쓰인 부분에 남긴 코멘트만 봐주시면 좋을 거 같아요!

2024-11-26 00:25 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/MediaSelectionDialog.kt
> +            )
preview에 적힌 코드대로 height값을 직접 주는 대신 padding(vertical= )을 사용하는 것을 추천드립니다!

2024-11-26 00:25 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/dialog/PhotoDeleteConfirmationDialog.kt
> +    }
위에 남긴 부분이랑 동일합니다 padding(vertical= ) 추천드립니다!

2024-11-26 05:28 UTC, merged