[UI/#22] 신고페이지 UI 구현
SOPT-all/35-COLLABORATION-ANDROID-SHINMUNGO pull request #33
Opened 2024-11-25 12:06 UTC by chrin05

## Related issue 🛠
- closed #22 

## Work Description ✏️
- 신고페이지 UI 작성
- 카메라 버튼 클릭 시 5분 count
- 폴더 클릭 시 사진 파일 추가
- 지도 버튼 클릭 시 주소 추가
- 내용 입력 기능 및 추천단어 버튼 구현
- 내용 5글자 이상 입력 시 휴대전화 자동 입력
- 신고 내용 공유 동의 버튼 구현

## Screenshot 📸
<img src="링크" width="360"/>
<img width="430" alt="image" src="https://github.com/user-attachments/assets/c83892f4-54e9-457a-9804-58bc5b88add3">

## Uncompleted Tasks 😅
> 아직 구현이 안됐거나 미흡한 부분이 있다면 작성해주세요.
- [ ] 폴더아이콘 -> 갤러리로 연결
- [ ] 지도아이콘 -> 지도 페이지로 연결
- [ ] 버튼 클릭 시 색상 변경...

## To Reviewers (Optional) 📢
> 리뷰어가 특별히 봐줬으면 하는 부분이 있다면 작성해주세요.

Topbar가 제 에뮬레이터에서만 짤려서 보이는 건지..제 코드가 이상한건지...모르겠습니다...
코드들이 깔끔하진 않은 거 같아서 피드백 주시면 바로 반영하겠습니다

2024-11-25 12:57 UTC, boiledeggg requested changes
너무 수고하셨습니다~
문자열 리소스화랑 반투명 색상 선언만 잘 수정해주시면 완벽할 것 같아요!
수정하시고 재요청 부탁드립니다~!!

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +            title = "불법주정차",
하드코딩 지양합니다!

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
뷰모델을 파라미터로 넘기지 말고 해당 컴포넌트에서 필요한 변수, 함수들만 따로 선언해주시는 것을 추천드립니다!
이렇게 선언하는 경우 불필요한 리컴포지션이 발생하고, 컴포넌트의 재사용성을 떨어뜨립니다!

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
> +            _content.value = _content.value + "소방차 전용구역 불법주차 신고입니다."
컨텍스트 접근이 어려운 뷰모델의 경우, `companion object`와 `const val`을 사용하여 선언된 상수를 활용하면 더욱 깔끔하고 유지보수성이 높은 코드로 관리할 수 있습니다!

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/CategoryGrid.kt
> +fun CategoryGrid(viewModel: ReportViewModel, modifier: Modifier = Modifier) {
앞서 뷰모델을 파라미터로 받지 않는 것을 추천한다고 했는데, 다른 파라미터들을 받는 예시를 보여드릴게요!
```suggestion
fun CategoryGrid(
      illegalParkingCategory: List<String>,
      updateSelectedCategory: (String) -> Unit,
      updateIsDropDownOpen: () -> Unit,
      modifier: Modifier = Modifier
) {
```

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportLocationSection.kt
> +    val location = viewModel.location.collectAsStateWithLifecycle("")
`""`은 왜 들어간건가요??

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhoneNumberSection.kt
> +                color = if (showPhoneNumber.value) ShinMunGoTheme.color.gray13 else Color(0x66121212)
`0x66121212`는 알파값이 포함된 색상인거 같은데, `opacity`라는 이름으로 알파값이 포함된 색상들 선언되어 있으니까 그걸로 수정해주세요~!!

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportSectionTitle.kt
> +    modifier: Modifier = Modifier
순서,,,,

2024-11-25 12:57 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ShowPhotoList.kt
> +                    .background(color = Color(0x99121212))
이 부분도 ShinMunGoTheme 색상으로 수정해주세요~

2024-11-25 13:47 UTC, yihwanggeun reviewed
코드를 보니까 고생을 아주 많이 하셨겠네요... 수고 많으셨습니다!

2024-11-25 13:47 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
> +            modifier = Modifier.size(24.dp)
코어에서 변경사항이 생기면 저희 모두한테 영향이 갈 수도 있을 것 같아서 얘기해주시면 좋을 것 같아요

2024-11-25 13:47 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    onClick = { /* 뒤로가기 */ }
뒤로 가기 부분도 Nav 설정과 함께 추가해주세요
제 코드 보면 뒤로 가기 부분 구현해두었는데 참고해주세요!

2024-11-25 13:47 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
궁금한 점이 있는데 ReportScreen에서 처음 Viewmodel 생성해주고 `ReportPhotoSection() : ReportViewModel()` 이런 방식으로 선언해주고 
다음에 ViewModel 할당 받으면 ViewModelProvider에서 알아서 사용중인 ViewModel을 제공해주는거로 아는데 혹시 맞을까요? 이게 맞다면 Parameter부분에서 다 삭제하고 각 Section에서 Provider에게 제공 받을 수 있지 않을까 싶습니다..

2024-11-25 13:47 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
@boiledEgg-s

2024-11-25 13:47 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhotoSection.kt
> +                onButtonClick = {
이 부분도 나중에는 제가 전달해주는 방식으로 사용될 예정이라 참고 부탁드려요!

2024-11-25 15:24 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportLocationSection.kt
> +    val location = viewModel.location.collectAsStateWithLifecycle("")
잘못들어간 것 같습니다..ㅎ

2024-11-25 15:24 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportPhoneNumberSection.kt
> +                color = if (showPhoneNumber.value) ShinMunGoTheme.color.gray13 else Color(0x66121212)
이거 바꾼다는걸 깜빡했네요.. 반영하겠습니다!

2024-11-25 15:32 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/core/designsystem/component/button/RoundCornerIconButton.kt
> +            modifier = Modifier.size(24.dp)
네! 다음부터는 신경쓰도록 하겠습니다

2024-11-25 15:59 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
처음 들어보는 방법이네요,, 
저는 ViewModel을 저렇게 파라미터로 넘기지 않아도, 하위 컴포저블에서 상위 컴포저블과 동일한 ViewModel 타입을 생성자 부분에 선언하면 새로운 뷰모델 객체를 사용하는 것이 아니라 상위 컴포저블에 선언된 ViewModel 객체를 사용하는 것으로 알고 있습니다!

```kotlin
@Composable
fun ParentView(
      viewModel: ReportViewModel = viewModel()
) {
      ChildView()
}

@Composable
fun ChildView(
      viewModel: ReportViewModel = viewModel()
)
```
위와 같은 경우에 ChildView의 뷰모델은 ParentView에서 선언된 뷰모델 객체를 사용하게 되는 것이죠!

2024-11-25 16:00 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
근데 저는 하위 컴포저블을 선언할 때 뷰모델 자체를 넘겨주는 것은 특히 코드 가독성 측면에서 좋지 않다고 생각해서 첫 코멘트를 남긴 것 입니다!

2024-11-25 16:05 UTC, boiledEgg-s approved these changes
너무 고생하셨어요~ 코드가 깔끔해서 읽기 편하네요ㅎㅎ
하드코딩 왠만하면 지양하고 상수화/리소스화 습관화해주시면 더할 나위없이 좋을 것 같습니다!

2024-11-25 16:05 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
> +        val value = _content.value.length >= 5
이런 숫자들도 상수화하면 좋을 것 같숩니다!

2024-11-25 16:20 UTC, jangsjw commented
앞에 분들이 너무 상세하게 리뷰해주셔서  그 부분들 보고 배워갑니다..! 고생하셨어요

2024-11-25 16:28 UTC, jangsjw approved these changes

2024-11-25 19:32 UTC, yihwanggeun commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
같은 말이었는데 제가 표현을 잘 못했네요!
역시 많이 아시니 설명도 찰떡같이 잘 하시는군요,,,,

2024-11-26 14:45 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +                    ReportPhotoSection(viewModel = viewModel)
제가 문해력이 부족해서 다른 말인줄 알았네요,,, 여튼 둘 다 맞다~

2024-11-26 15:11 UTC, boiledEgg-s approved these changes
너무 고생많으셨어요~!! 하드코딩이랑 주석만 한번더 확인해주세요!
하면 바로 머지합시당!

2024-11-26 15:11 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +    val isPostButtonActive = viewModel.isPostButtonActive.collectAsStateWithLifecycle()
앱잼때는 꼭 상태 클래스를 만들어서 관리해보세요!

2024-11-26 15:11 UTC, boiledeggg commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportViewModel.kt
> +        val value = _content.value.length >= 5
상수화한거 넣어주셔요ㅎ

2024-11-26 15:11 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/DropdownCategory.kt
> +                ambientColor = Color(0x1A000000)
이 부분은 색상에 없나요? 없다면 Color 파일에만 선언해두고 사용합시다!

2024-11-26 15:11 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportContentSection.kt
> +//                onValueChange = { viewModel.updateContent(it) },
주석 삭제해주세요~

2024-11-26 15:11 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportContentSection.kt
> +//                onButtonClick = { viewModel.updateIsRecommendWord() }
여기도~

2024-11-26 15:11 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/shinmungo/presentation/report/component/ReportLocationSection.kt
> +//    val location = viewModel.location.collectAsStateWithLifecycle()
얘도 삭제!

2024-11-26 15:12 UTC, chrin05 commented on app/src/main/java/com/sopt/shinmungo/presentation/report/ReportScreen.kt
> +    val isPostButtonActive = viewModel.isPostButtonActive.collectAsStateWithLifecycle()
이번에 하면서 절실하게 필요성을 느꼈습니다..

2024-11-26 15:22 UTC, merged